namespace OpenPlanTrace;

public enum PlanArtifactKind
{
    Unknown = 0,
    Document,
    Pages,
    Primitives,
    Layers,
    RasterImages,
    PdfImages,
    SheetRegions,
    TitleBlocks,
    Calibration,
    Dimensions,
    Annotations,
    GridAxes,
    GridBays,
    MeasurementConsistency,
    DimensionChains,
    SurfacePatterns,
    WallCandidates,
    Walls,
    WallEvidence,
    WallGraph,
    TopologySpans,
    Openings,
    Rooms,
    RoomAdjacency,
    ObjectCandidates,
    ObjectGroups,
    ObjectAggregates,
    RoutingBarriers,
    RoutingPassages,
    RoutingObstacles,
    RoutingRoomUseHints,
    RoutingSuppressedObjects,
    RoutingIgnoredObjects,
    VisualAiClassifications,
    LayerConsistency,
    Diagnostics,
    Quality
}
