namespace OpenPlanTrace;

public sealed record BenchmarkCounts(
    int Pages,
    int Regions,
    int Dimensions,
    int Annotations,
    int AnnotationReferences,
    int GridAxes,
    int GridBaySpacings,
    int SurfacePatterns,
    int Walls,
    int WallNodes,
    int WallEdges,
    int Rooms,
    int RoomAdjacencies,
    int RoomClusters,
    int Openings,
    int Objects,
    int ObjectGroups,
    int ObjectAggregates,
    int RoutingItems,
    int RoutingSuppressedObjects,
    int Diagnostics,
    int DiagnosticWarnings,
    int DiagnosticErrors,
    PlanScanQualityGrade QualityGrade,
    double QualityConfidence,
    bool QualityRequiresReview,
    int QualityIssues,
    bool HasReliableCalibration,
    int MeasurementCheckedCount,
    int MeasurementConsistentCount,
    int MeasurementOutlierCount,
    double? MeasurementSelectedMillimetersPerDrawingUnit,
    double? MeasurementMedianMillimetersPerDrawingUnit,
    double? MeasurementScaleSpreadRatio,
    double MeasurementConsistencyConfidence)
{
    public static BenchmarkCounts From(PlanScanResult result) =>
        new(
            result.Document.Pages.Count,
            result.SheetRegions.Count,
            result.Dimensions.Count,
            result.Annotations.Count,
            result.Annotations.Sum(annotation => annotation.Items.Sum(item => item.References.Count)),
            result.GridAxes.Count,
            result.GridBaySpacings.Count,
            result.SurfacePatterns.Count,
            result.Walls.Count,
            result.WallGraph.Nodes.Count,
            result.WallGraph.Edges.Count,
            result.Rooms.Count,
            result.RoomAdjacencyGraph.Edges.Count,
            result.RoomAdjacencyGraph.Clusters.Count,
            result.Openings.Count,
            result.ObjectCandidates.Count,
            result.ObjectGroups.Count,
            result.ObjectAggregates.Count,
            RoutingItemCount(result.RoutingLayer),
            result.RoutingLayer.SuppressedObjects.Count,
            result.Diagnostics.Messages.Count,
            result.Diagnostics.Messages.Count(message => message.Severity == DiagnosticSeverity.Warning),
            result.Diagnostics.Messages.Count(message => message.Severity == DiagnosticSeverity.Error),
            result.Quality.Grade,
            result.Quality.OverallConfidence.Value,
            result.Quality.RequiresReview,
            result.Quality.Issues.Count,
            result.Calibration.HasReliableMeasurementScale,
            result.MeasurementConsistency.CheckedCount,
            result.MeasurementConsistency.ConsistentCount,
            result.MeasurementConsistency.OutlierCount,
            result.MeasurementConsistency.SelectedMillimetersPerDrawingUnit,
            result.MeasurementConsistency.MedianDimensionMillimetersPerDrawingUnit,
            result.MeasurementConsistency.DimensionScaleSpreadRatio,
            result.MeasurementConsistency.Confidence.Value);

    public static BenchmarkCounts Empty { get; } =
        new(
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PlanScanQualityGrade.Unknown,
            0,
            true,
            0,
            false,
            0,
            0,
            0,
            null,
            null,
            null,
            0);

    private static int RoutingItemCount(PlanRoutingLayer routingLayer) =>
        routingLayer.Barriers.Count
        + routingLayer.Passages.Count
        + routingLayer.Obstacles.Count
        + routingLayer.RoomUseHints.Count;
}
